name: LZT Sniper

on:
  workflow_dispatch:
  schedule:
    - cron: "* * * * *"  # every minute

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout repo
        uses: actions/checkout@v3

      - name: 🐍 Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: 📦 Install dependencies
        run: |
          pip install -r requirements.txt
          python -m playwright install

      - name: 🚀 Run bot
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: python lzt_sniper.py
